name: "ReadTheDocs Trigger"
description: "Trigger a build on ReadTheDocs"
inputs:
  webhook_id:
    description: "The webhook ID from ReadTheDocs. The API URL will have the form: readthedocs.org/api/v2/webhook/{webhook_id}/"
    required: true
  webhook_token:
    description: "The webhook token from ReadTheDocs"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
